import Sample from '../../../shared/assets/images/genre/sampleImage.png';
import JokerHeadIcon from '../../../shared/assets/images/genre/jokerheadicon.png'

export const roomData = [
    {
      id: 1,
      title: '키이스케이프',
      location: '강남',
      description: '가격 정보',
      levelNum: 4.4,
      levelText: '어려움',
      playTime: 60,
      genre: '장르',
      icon: JokerHeadIcon,
      image: Sample,
    },
    {
      id: 2,
      title: '키이스케이프',
      location: '강남',
      description: '가격 정보',
      levelNum: 4.4,
      levelText: '어려움',
      playTime: 60,
      genre: '장르',
      icon: JokerHeadIcon,
      image: Sample,
    },
    {
      id: 3,
      title: '키이스케이프',
      location: '강남',
      description: '가격 정보',
      levelNum: 4.4,
      levelText: '어려움',
      playTime: 60,
      genre: '장르',
      icon: JokerHeadIcon,
      image: Sample,
    },
    {
      id: 4,
      title: '키이스케이프',
      location: '강남',
      description: '가격 정보',
      levelNum: 4.4,
      levelText: '어려움',
      playTime: 60,
      genre: '장르',
      icon: JokerHeadIcon,
      image: Sample,
    },
    {
      id: 5,
      title: '키이스케이프',
      location: '강남',
      description: '가격 정보',
      levelNum: 4.4,
      levelText: '어려움',
      playTime: 60,
      genre: '장르',
      icon: JokerHeadIcon,
      image: Sample,
    },
    {
      id: 6,
      title: '키이스케이프',
      location: '강남',
      description: '가격 정보',
      levelNum: 4.4,
      levelText: '어려움',
      playTime: 60,
      genre: '장르',
      icon: JokerHeadIcon,
      image: Sample,
    },
    {
      id: 7,
      title: '키이스케이프',
      location: '강남',
      description: '가격 정보',
      levelNum: 4.4,
      levelText: '어려움',
      playTime: 60,
      genre: '장르',
      icon: JokerHeadIcon,
      image: Sample,
    },
    {
      id: 8,
      title: '키이스케이프',
      location: '강남',
      description: '가격 정보',
      levelNum: 4.4,
      levelText: '어려움',
      playTime: 60,
      genre: '장르',
      icon: JokerHeadIcon,
      image: Sample,
    },
  ];