export const locationList = [
  { id: 0, name: '전체'},
  { id: 1, name: '홍대'},
  { id: 2, name: '강남'},
  { id: 3, name: '건대'},
  { id: 4, name: '신촌'},
  { id: 5, name: '대학로'},
  { id: 6, name: '잠실'},
  { id: 7, name: '신림'},
  { id: 8, name: '인천'},
  { id: 9, name: '수원'},
  { id: 10, name: '성남'},
  { id: 11, name: '일산'},
  { id: 12, name: '부천'},
  { id: 13, name: '의정부'},
  { id: 14, name: '평택'},
  { id: 15, name: '안산'},
];
